version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DBNAME}
    networks:
      - todo-app

networks:
  todo-app: